import jsPDF from 'jspdf';
import { TravelPlan } from '@/types/agent';

const colors = {
  bgDark: [11, 15, 26] as [number, number, number],
  bgMid: [17, 24, 39] as [number, number, number],
  bgLight: [26, 31, 46] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  textPrimary: [230, 235, 245] as [number, number, number],
  textSecondary: [148, 163, 184] as [number, number, number],
  textMuted: [100, 116, 139] as [number, number, number],
  accent: [99, 145, 255] as [number, number, number],
  accentGold: [250, 204, 80] as [number, number, number],
  cardBg: [30, 38, 58] as [number, number, number],
  separator: [45, 55, 75] as [number, number, number],
};

const dayTabColors = [
  [99, 145, 255] as [number, number, number],
  [250, 204, 80] as [number, number, number],
  [134, 239, 172] as [number, number, number],
  [249, 115, 115] as [number, number, number],
  [196, 167, 255] as [number, number, number],
  [253, 186, 116] as [number, number, number],
];

const formatCurrency = (amount: number, freeLabel = true) => {
  if (amount === 0 && freeLabel) return 'Free';
  return `INR ${amount.toLocaleString('en-IN')}`;
};

const formatBudgetStatus = (status: TravelPlan['budgetStatus']) => {
  if (status === 'approved') return 'Within budget';
  if (status === 'warning') return 'Adjusted budget';
  return 'Over budget';
};

export function buildTravelPDF(plan: TravelPlan) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const pageBottom = pageHeight - 20;
  const lineHeight = 4.6;
  let y = 0;

  const addPageBg = () => {
    const bandHeight = pageHeight / 3;
    doc.setFillColor(...colors.bgDark);
    doc.rect(0, 0, pageWidth, bandHeight, 'F');
    doc.setFillColor(...colors.bgMid);
    doc.rect(0, bandHeight, pageWidth, bandHeight, 'F');
    doc.setFillColor(...colors.bgLight);
    doc.rect(0, bandHeight * 2, pageWidth, bandHeight + 1, 'F');
  };

  const addFooter = () => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    doc.setTextColor(...colors.textMuted);
    doc.text('Generated by TravelAI Planner', pageWidth / 2, pageHeight - 8, { align: 'center' });
  };

  const checkPage = (needed: number) => {
    if (y + needed <= pageBottom) return;
    doc.addPage();
    addPageBg();
    addFooter();
    y = 20;
  };

  const splitLines = (
    text: string,
    width: number,
    fontSize: number,
    fontStyle: 'normal' | 'bold' | 'italic' = 'normal'
  ) => {
    doc.setFont('helvetica', fontStyle);
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text || '', Math.max(width, 10));
  };

  const drawSectionHeader = (title: string) => {
    checkPage(16);
    doc.setFillColor(...colors.accent);
    doc.roundedRect(margin, y - 5, contentWidth, 11, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...colors.bgDark);
    doc.text(title, margin + 6, y + 2);
    y += 14;
  };

  addPageBg();

  y = 28;
  doc.setFillColor(...colors.accent);
  doc.rect(margin, 12, 30, 2.5, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(32);
  doc.setTextColor(...colors.white);
  doc.text('Trip', margin, y);

  const tripWidth = doc.getTextWidth('Trip ');
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.textSecondary);
  doc.text('Itinerary', margin + tripWidth, y);

  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...colors.accent);
  doc.text('Start Date', margin, y);
  doc.text('End Date', pageWidth / 2 + 10, y);

  doc.setDrawColor(...colors.separator);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 22, y, pageWidth / 2 - 5, y);
  doc.line(pageWidth / 2 + 28, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);

  doc.setFontSize(7);
  doc.setTextColor(...colors.textPrimary);
  if (plan.itinerary.length > 0) {
    doc.text(plan.itinerary[0].date, margin + 24, y - 1);
    doc.text(plan.itinerary[plan.itinerary.length - 1].date, pageWidth / 2 + 30, y - 1);
  }

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(...colors.accent);
  doc.text('Destination', margin, y);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 24, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);
  doc.setFontSize(7);
  doc.setTextColor(...colors.textPrimary);
  doc.text(plan.destination, margin + 26, y - 1);

  y += 10;
  const summaryCardY = y - 4;
  const summaryPad = 5;
  const summaryLeftX = margin + summaryPad;
  const summaryMidX = pageWidth / 2 + 3;
  const summaryColWidth = contentWidth / 2 - 8;
  const transportSummary = plan.transport
    ? `${plan.transport.type} - ${plan.transport.from} to ${plan.transport.to}`
    : 'Transport details unavailable';
  const hotelSummary = plan.hotel
    ? `${plan.hotel.name} - ${plan.hotel.location}`
    : 'Accommodation details unavailable';
  const transportLines = splitLines(transportSummary, summaryColWidth - 6, 7);
  const hotelLines = splitLines(hotelSummary, summaryColWidth - 6, 7);
  const summaryBodyHeight = Math.max(transportLines.length, hotelLines.length) * lineHeight;
  const summaryHeight = Math.max(20, 9 + summaryBodyHeight + 4);

  doc.setFillColor(...colors.cardBg);
  doc.roundedRect(margin, summaryCardY, contentWidth, summaryHeight, 2, 2, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(...colors.accent);
  doc.text('Transport', summaryLeftX, y + 1);
  doc.text('Hotel', summaryMidX, y + 1);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...colors.textPrimary);
  doc.text(transportLines, summaryLeftX, y + 6);
  doc.text(hotelLines, summaryMidX, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.accentGold);
  if (plan.transport) {
    doc.text(formatCurrency(plan.transport.price, false), summaryLeftX, y + 6 + transportLines.length * lineHeight + 1);
  }
  if (plan.hotel) {
    doc.text(`${formatCurrency(plan.hotel.pricePerNight, false)}/night`, summaryMidX, y + 6 + hotelLines.length * lineHeight + 1);
  }

  y = summaryCardY + summaryHeight + 8;

  const tabWidth = 24;
  const tabX = margin;
  const contentX = tabX + tabWidth + 6;
  const cardRight = pageWidth - margin;
  const innerPad = 11;
  const timeX = contentX + innerPad;
  const activityX = contentX + 34;
  const priceRightX = cardRight - innerPad;
  const priceColumnWidth = 33;
  const activityTextWidth = Math.max(50, priceRightX - activityX - priceColumnWidth);

  for (const day of plan.itinerary) {
    const activityBlocks = day.activities.map((activity, index) => {
      const nameLines = splitLines(activity.name, activityTextWidth, 9.5, 'bold');
      const travelText = index > 0 && activity.travelFromPrevious?.travelTime
        ? `${activity.travelFromPrevious.distanceKm} km • ${activity.travelFromPrevious.travelTime} • ${activity.travelFromPrevious.mode}`
        : null;
      const travelLines = travelText ? splitLines(travelText, activityTextWidth + 8, 7.5) : [];

      return {
        activity,
        nameLines,
        travelLines,
        travelHeight: travelLines.length > 0 ? travelLines.length * 3.8 + 1.5 : 0,
        textHeight: Math.max(8, nameLines.length * lineHeight),
      };
    });

    const mealBlocks = [day.meals?.lunch, day.meals?.dinner]
      .filter(Boolean)
      .map((meal) => ({
        lines: splitLines(`${meal!.name} (${meal!.cuisine})`, activityTextWidth, 9),
        cost: meal!.costPerPerson,
      }));

    const headerHeight = 17;
    const activityHeight = activityBlocks.reduce((total, block) => total + block.travelHeight + block.textHeight + 2.5, 0);
    const mealHeight = mealBlocks.reduce((total, block) => total + Math.max(8, block.lines.length * lineHeight) + 2.5, 0);
    const neededHeight = Math.max(40, headerHeight + activityHeight + mealHeight + 12);

    checkPage(neededHeight + 2);

    const tabColor = dayTabColors[(day.day - 1) % dayTabColors.length];
    const blockStartY = y;

    doc.setFillColor(...colors.cardBg);
    doc.roundedRect(contentX - 2, blockStartY, cardRight - contentX + 2, neededHeight, 2, 2, 'F');

    doc.setFillColor(...tabColor);
    doc.roundedRect(tabX, blockStartY, tabWidth, neededHeight, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...colors.bgDark);
    doc.text(`DAY ${day.day}`, tabX + tabWidth / 2, blockStartY + neededHeight / 2, {
      align: 'center',
      angle: 90,
    });

    let ay = blockStartY + 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(...colors.textPrimary);
    doc.text(day.theme || `Day ${day.day} Plan`, timeX, ay);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...colors.textMuted);
    doc.text(`${day.date} • ${day.weather.temperature}°C • ${day.weather.condition}`, priceRightX, ay, { align: 'right' });

    ay += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(...colors.textSecondary);
    doc.text('Time', timeX, ay);
    doc.text('Activity', activityX, ay);
    doc.text('Cost', priceRightX, ay, { align: 'right' });

    ay += 3;
    doc.setDrawColor(...colors.separator);
    doc.setLineWidth(0.3);
    doc.line(timeX, ay, cardRight - innerPad, ay);
    ay += 6;

    for (const block of activityBlocks) {
      if (block.travelLines.length > 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...colors.textMuted);
        doc.text(block.travelLines, activityX, ay);
        ay += block.travelHeight;
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...colors.textMuted);
      doc.text(block.activity.timeSlot || '—', timeX, ay);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...colors.textPrimary);
      doc.text(block.nameLines, activityX, ay);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...tabColor);
      doc.text(formatCurrency(block.activity.cost), priceRightX, ay, { align: 'right' });

      ay += block.textHeight + 2.5;
    }

    for (const [index, block] of mealBlocks.entries()) {
      const mealLabel = index === 0 ? 'Lunch' : 'Dinner';

      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8.5);
      doc.setTextColor(...colors.textMuted);
      doc.text(mealLabel, timeX, ay);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...colors.textPrimary);
      doc.text(block.lines, activityX, ay);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.accentGold);
      doc.text(formatCurrency(block.cost, false), priceRightX, ay, { align: 'right' });

      ay += Math.max(8, block.lines.length * lineHeight) + 2.5;
    }

    doc.setDrawColor(...colors.separator);
    doc.setLineWidth(0.2);
    doc.line(timeX, ay - 1, cardRight - innerPad, ay - 1);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...colors.textSecondary);
    doc.text('Day Total', timeX, ay + 4);

    doc.setTextColor(...colors.accentGold);
    doc.text(formatCurrency(day.totalCost, false), priceRightX, ay + 4, { align: 'right' });

    y = blockStartY + neededHeight + 8;
  }

  if (plan.budgetBreakdown) {
    drawSectionHeader('Cost Breakdown');

    const items = [
      ['Accommodation', plan.budgetBreakdown.accommodation],
      ['Transport', plan.budgetBreakdown.transport],
      ['Activities', plan.budgetBreakdown.activities],
      ['Food', plan.budgetBreakdown.food],
      ['Local Transport', plan.budgetBreakdown.localTransport || 0],
      ['Miscellaneous', plan.budgetBreakdown.miscellaneous],
    ] as const;

    for (let i = 0; i < items.length; i++) {
      const [label, value] = items[i];
      checkPage(10);

      if (i % 2 === 0) {
        doc.setFillColor(...colors.cardBg);
        doc.rect(margin, y - 5, contentWidth, 9, 'F');
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...colors.textPrimary);
      doc.text(label, margin + 8, y);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.accentGold);
      doc.text(formatCurrency(value, false), pageWidth - margin - 8, y, { align: 'right' });
      y += 9;
    }

    doc.setDrawColor(...colors.accent);
    doc.setLineWidth(0.5);
    doc.line(margin, y - 2, pageWidth - margin, y - 2);
    y += 5;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...colors.accent);
    doc.text('TOTAL', margin + 8, y);

    doc.setTextColor(...colors.accentGold);
    doc.text(formatCurrency(plan.totalCost, false), pageWidth - margin - 8, y, { align: 'right' });

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...colors.textMuted);
    doc.text(`Budget: ${formatCurrency(plan.totalBudget, false)} • ${formatBudgetStatus(plan.budgetStatus)}`, margin + 6, y);
    y += 8;
  }

  if (plan.agentDecisions) {
    drawSectionHeader('Agent Decision Summary');

    const agentEntries = [
      { key: 'weather_agent', label: 'Weather Agent' },
      { key: 'budget_agent', label: 'Budget Agent' },
      { key: 'location_agent', label: 'Location Agent' },
      { key: 'itinerary_agent', label: 'Itinerary Agent' },
      { key: 'food_agent', label: 'Food Agent' },
      { key: 'transport_agent', label: 'Transport Agent' },
    ] as const;

    const labelX = margin + 6;
    const labelWidth = 42;
    const textX = labelX + labelWidth + 6;
    const textWidth = pageWidth - margin - 6 - textX;

    for (const entry of agentEntries) {
      const decision = plan.agentDecisions[entry.key];
      if (!decision) continue;

      const decisionLines = splitLines(decision, textWidth, 8.5);
      const rowHeight = Math.max(12, 7 + decisionLines.length * lineHeight);
      checkPage(rowHeight + 3);

      doc.setFillColor(...colors.cardBg);
      doc.roundedRect(margin, y - 4, contentWidth, rowHeight, 1, 1, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...colors.accent);
      doc.text(entry.label, labelX, y + 1);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...colors.textPrimary);
      doc.text(decisionLines, textX, y + 1);

      y += rowHeight + 3;
    }
  }

  if (plan.tips && plan.tips.length > 0) {
    drawSectionHeader('Travel Tips');

    for (const tip of plan.tips) {
      const tipLines = splitLines(`• ${tip}`, contentWidth - 12, 10);
      const tipHeight = tipLines.length * 5 + 3;
      checkPage(tipHeight + 2);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...colors.textPrimary);
      doc.text(tipLines, margin + 6, y);
      y += tipHeight;
    }
  }

  addFooter();
  return doc;
}

export function generateTravelPDF(plan: TravelPlan) {
  const doc = buildTravelPDF(plan);
  doc.save(`TravelPlan-${plan.destination.replace(/\s+/g, '-')}.pdf`);
}
