import jsPDF from 'jspdf';
import { TravelPlan } from '@/types/agent';

export function generateTravelPDF(plan: TravelPlan) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  const colors = {
    white: [255, 255, 255] as [number, number, number],
    black: [30, 30, 30] as [number, number, number],
    gray: [130, 130, 130] as [number, number, number],
    lightGray: [200, 200, 200] as [number, number, number],
    orange: [230, 120, 70] as [number, number, number],
    orangeLight: [245, 200, 170] as [number, number, number],
    orangeBg: [250, 235, 225] as [number, number, number],
  };

  const dayTabColors = [
    [230, 120, 70] as [number, number, number],   // orange
    [100, 160, 200] as [number, number, number],   // blue
    [180, 140, 100] as [number, number, number],   // tan
    [160, 190, 120] as [number, number, number],   // green
    [190, 130, 170] as [number, number, number],   // purple
    [210, 170, 80] as [number, number, number],    // gold
  ];

  const addPageBg = () => {
    doc.setFillColor(...colors.white);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  };

  const checkPage = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      addPageBg();
      y = 20;
    }
  };

  const addFooter = () => {
    doc.setFontSize(6);
    doc.setTextColor(180, 180, 180);
    doc.text('Generated by TravelAI Planner', pageWidth / 2, pageHeight - 8, { align: 'center' });
  };

  // ===== PAGE 1 BACKGROUND =====
  addPageBg();

  // ===== HEADER: "Trip Itinerary" =====
  y = 28;

  // Orange decorative line at top
  doc.setFillColor(...colors.orange);
  doc.rect(margin, 12, 30, 2.5, 'F');

  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.black);
  doc.text('Trip', margin, y);

  const tripWidth = doc.getTextWidth('Trip ');
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.gray);
  doc.text('Itinerary', margin + tripWidth, y);

  // ===== START/END DATE & DESTINATION =====
  y += 12;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.orange);
  doc.text('Start Date', margin, y);
  doc.text('End Date', pageWidth / 2 + 10, y);

  // Dotted lines
  doc.setDrawColor(...colors.lightGray);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 22, y, pageWidth / 2 - 5, y);
  doc.line(pageWidth / 2 + 28, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);

  // Fill in dates if available
  doc.setFontSize(7);
  doc.setTextColor(...colors.black);
  if (plan.itinerary.length > 0) {
    doc.text(plan.itinerary[0].date, margin + 24, y - 1);
    doc.text(plan.itinerary[plan.itinerary.length - 1].date, pageWidth / 2 + 30, y - 1);
  }

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(...colors.orange);
  doc.text('Destination', margin, y);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 24, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);
  doc.setFontSize(7);
  doc.setTextColor(...colors.black);
  doc.text(plan.destination, margin + 26, y - 1);

  // ===== TRANSPORT & HOTEL SUMMARY =====
  y += 10;
  doc.setFillColor(...colors.orangeBg);
  doc.roundedRect(margin, y - 4, contentWidth, 18, 2, 2, 'F');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.orange);

  const summaryLeft = margin + 4;
  const summaryRight = pageWidth / 2 + 5;

  if (plan.transport) {
    doc.text('Transport', summaryLeft, y + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.black);
    doc.text(`${plan.transport.type} — ${plan.transport.from} to ${plan.transport.to}`, summaryLeft, y + 6);
    doc.setTextColor(...colors.orange);
    doc.setFont('helvetica', 'bold');
    doc.text(`₹${plan.transport.cost.toLocaleString()}`, summaryLeft, y + 11);
  }

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.orange);
  if (plan.hotel) {
    doc.text('Hotel', summaryRight, y + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.black);
    doc.text(`${plan.hotel.name} — ${plan.hotel.location}`, summaryRight, y + 6);
    doc.setTextColor(...colors.orange);
    doc.setFont('helvetica', 'bold');
    doc.text(`₹${plan.hotel.pricePerNight.toLocaleString()}/night`, summaryRight, y + 11);
  }

  y += 20;

  // ===== DAY-WISE ITINERARY =====
  const tabWidth = 18;
  const tabX = margin;
  const contentX = margin + tabWidth + 4;
  const actContentWidth = contentWidth - tabWidth - 4;

  for (const day of plan.itinerary) {
    const activityLines = day.activities.length;
    const mealLines = (day.meals?.lunch ? 1 : 0) + (day.meals?.dinner ? 1 : 0);
    const neededHeight = 14 + (activityLines + mealLines) * 8 + 6;

    checkPage(neededHeight);

    const tabColor = dayTabColors[(day.day - 1) % dayTabColors.length];
    const blockStartY = y;

    // Vertical colored tab
    doc.setFillColor(...tabColor);
    doc.roundedRect(tabX, blockStartY, tabWidth, neededHeight - 2, 2, 2, 'F');

    // Day label (rotated)
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    const dayLabel = `DAY ${day.day}`;
    const tabCenterY = blockStartY + (neededHeight - 2) / 2;
    doc.text(dayLabel, tabX + tabWidth / 2, tabCenterY, { align: 'center', angle: 90 });

    // Activity header
    let ay = blockStartY + 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.black);
    doc.text('Time', contentX, ay);
    doc.text('Activity', contentX + 22, ay);

    // Weather + date info
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.gray);
    doc.text(`${day.date}  •  ${day.weather.temperature}°C, ${day.weather.condition}`, contentX + 60, ay);

    ay += 3;

    // Thin separator line
    doc.setDrawColor(...colors.lightGray);
    doc.setLineWidth(0.3);
    doc.line(contentX, ay, pageWidth - margin, ay);

    ay += 5;

    // Activities
    for (const act of day.activities) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');

      // Time
      doc.setTextColor(...colors.gray);
      const timeStr = act.timeSlot || '—';
      doc.text(timeStr, contentX, ay);

      // Activity name
      doc.setTextColor(...colors.black);
      const actName = act.name;
      const truncatedName = doc.splitTextToSize(actName, actContentWidth - 55);
      doc.text(truncatedName[0], contentX + 22, ay);

      // Price
      const costStr = act.cost === 0 ? 'Free' : `₹${act.cost.toLocaleString()}`;
      doc.setTextColor(...tabColor);
      doc.setFont('helvetica', 'bold');
      doc.text(costStr, pageWidth - margin, ay, { align: 'right' });

      ay += 7;
    }

    // Meals
    if (day.meals?.lunch) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...colors.gray);
      doc.text('Lunch', contentX, ay);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.black);
      doc.text(`${day.meals.lunch.name} (${day.meals.lunch.cuisine})`, contentX + 22, ay);
      doc.setTextColor(...tabColor);
      doc.setFont('helvetica', 'bold');
      doc.text(`₹${day.meals.lunch.costPerPerson}`, pageWidth - margin, ay, { align: 'right' });
      ay += 7;
    }
    if (day.meals?.dinner) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...colors.gray);
      doc.text('Dinner', contentX, ay);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.black);
      doc.text(`${day.meals.dinner.name} (${day.meals.dinner.cuisine})`, contentX + 22, ay);
      doc.setTextColor(...tabColor);
      doc.setFont('helvetica', 'bold');
      doc.text(`₹${day.meals.dinner.costPerPerson}`, pageWidth - margin, ay, { align: 'right' });
      ay += 7;
    }

    y = ay + 6;
  }

  // ===== COST BREAKDOWN =====
  if (plan.budgetBreakdown) {
    checkPage(55);
    y += 2;

    // Section header
    doc.setFillColor(...colors.orange);
    doc.roundedRect(margin, y - 4, contentWidth, 8, 1, 1, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Cost Breakdown', margin + 4, y + 1);
    y += 10;

    const items = [
      ['Accommodation', plan.budgetBreakdown.accommodation],
      ['Transport', plan.budgetBreakdown.transport],
      ['Activities', plan.budgetBreakdown.activities],
      ['Food', plan.budgetBreakdown.food],
      ['Local Transport', plan.budgetBreakdown.localTransport || 0],
      ['Miscellaneous', plan.budgetBreakdown.miscellaneous],
    ] as const;

    for (let i = 0; i < items.length; i++) {
      const [label, val] = items[i];

      // Alternate row background
      if (i % 2 === 0) {
        doc.setFillColor(248, 248, 248);
        doc.rect(margin, y - 4, contentWidth, 7, 'F');
      }

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.black);
      doc.text(label, margin + 4, y);
      doc.setFont('helvetica', 'bold');
      doc.text(`₹${val.toLocaleString()}`, pageWidth - margin, y, { align: 'right' });
      y += 7;
    }

    // Total line
    doc.setDrawColor(...colors.orange);
    doc.setLineWidth(0.5);
    doc.line(margin, y - 2, pageWidth - margin, y - 2);
    y += 3;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.orange);
    doc.text('TOTAL', margin + 4, y);
    doc.text(`₹${plan.totalCost.toLocaleString()}`, pageWidth - margin, y, { align: 'right' });

    // Budget status
    y += 6;
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.gray);
    const statusText = plan.budgetStatus === 'approved'
      ? '✓ Within Budget'
      : plan.budgetStatus === 'warning'
        ? '⚠ Tight Budget'
        : '✗ Over Budget';
    doc.text(`Budget: ₹${plan.totalBudget.toLocaleString()}  •  ${statusText}`, margin + 4, y);
    y += 10;
  }

  // ===== TIPS =====
  if (plan.tips && plan.tips.length > 0) {
    checkPage(20);

    doc.setFillColor(...colors.orangeBg);
    doc.roundedRect(margin, y - 4, contentWidth, 8, 1, 1, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.orange);
    doc.text('Travel Tips', margin + 4, y + 1);
    y += 10;

    for (const tip of plan.tips) {
      checkPage(10);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.black);
      const lines = doc.splitTextToSize(`• ${tip}`, contentWidth - 8);
      doc.text(lines, margin + 4, y);
      y += lines.length * 4.5 + 2;
    }
  }

  // ===== FOOTER =====
  addFooter();

  doc.save(`TravelPlan-${plan.destination.replace(/\s+/g, '-')}.pdf`);
}
