import jsPDF from 'jspdf';
import { TravelPlan } from '@/types/agent';

export function generateTravelPDF(plan: TravelPlan) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  // Dark navy palette
  const colors = {
    bgDark: [11, 15, 26] as [number, number, number],       // #0B0F1A
    bgMid: [17, 24, 39] as [number, number, number],        // #111827
    bgLight: [26, 31, 46] as [number, number, number],       // #1A1F2E
    white: [255, 255, 255] as [number, number, number],
    textPrimary: [230, 235, 245] as [number, number, number], // bright white-blue
    textSecondary: [148, 163, 184] as [number, number, number], // slate-400
    textMuted: [100, 116, 139] as [number, number, number],    // slate-500
    accent: [99, 145, 255] as [number, number, number],       // bright blue
    accentGold: [250, 204, 80] as [number, number, number],   // warm gold
    cardBg: [30, 38, 58] as [number, number, number],         // slightly lighter card
    separator: [45, 55, 75] as [number, number, number],      // subtle line
  };

  const dayTabColors = [
    [99, 145, 255] as [number, number, number],    // blue
    [250, 204, 80] as [number, number, number],    // gold
    [134, 239, 172] as [number, number, number],   // green
    [249, 115, 115] as [number, number, number],   // red
    [196, 167, 255] as [number, number, number],   // purple
    [253, 186, 116] as [number, number, number],   // orange
  ];

  const addPageBg = () => {
    // Gradient-like background using bands
    const bandHeight = pageHeight / 3;
    doc.setFillColor(...colors.bgDark);
    doc.rect(0, 0, pageWidth, bandHeight, 'F');
    doc.setFillColor(...colors.bgMid);
    doc.rect(0, bandHeight, pageWidth, bandHeight, 'F');
    doc.setFillColor(...colors.bgLight);
    doc.rect(0, bandHeight * 2, pageWidth, bandHeight + 1, 'F');
  };

  const checkPage = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      addPageBg();
      addFooter();
      y = 20;
    }
  };

  const addFooter = () => {
    doc.setFontSize(6);
    doc.setTextColor(...colors.textMuted);
    doc.text('Generated by TravelAI Planner', pageWidth / 2, pageHeight - 8, { align: 'center' });
  };

  // ===== PAGE 1 BACKGROUND =====
  addPageBg();

  // ===== HEADER =====
  y = 28;

  // Accent decorative line
  doc.setFillColor(...colors.accent);
  doc.rect(margin, 12, 30, 2.5, 'F');

  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.white);
  doc.text('Trip', margin, y);

  const tripWidth = doc.getTextWidth('Trip ');
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.textSecondary);
  doc.text('Itinerary', margin + tripWidth, y);

  // ===== START/END DATE & DESTINATION =====
  y += 12;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...colors.accent);
  doc.text('Start Date', margin, y);
  doc.text('End Date', pageWidth / 2 + 10, y);

  doc.setDrawColor(...colors.separator);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 22, y, pageWidth / 2 - 5, y);
  doc.line(pageWidth / 2 + 28, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);

  doc.setFontSize(7);
  doc.setTextColor(...colors.textPrimary);
  if (plan.itinerary.length > 0) {
    doc.text(plan.itinerary[0].date, margin + 24, y - 1);
    doc.text(plan.itinerary[plan.itinerary.length - 1].date, pageWidth / 2 + 30, y - 1);
  }

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(...colors.accent);
  doc.text('Destination', margin, y);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(margin + 24, y, pageWidth - margin, y);
  doc.setLineDashPattern([], 0);
  doc.setFontSize(7);
  doc.setTextColor(...colors.textPrimary);
  doc.text(plan.destination, margin + 26, y - 1);

  // ===== TRANSPORT & HOTEL SUMMARY =====
  y += 10;
  doc.setFillColor(...colors.cardBg);
  doc.roundedRect(margin, y - 4, contentWidth, 18, 2, 2, 'F');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.accent);

  const summaryLeft = margin + 4;
  const summaryRight = pageWidth / 2 + 5;

  if (plan.transport) {
    doc.text('Transport', summaryLeft, y + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.textPrimary);
    doc.text(`${plan.transport.type} — ${plan.transport.from} to ${plan.transport.to}`, summaryLeft, y + 6);
    doc.setTextColor(...colors.accentGold);
    doc.setFont('helvetica', 'bold');
    doc.text(`₹${plan.transport.price.toLocaleString()}`, summaryLeft, y + 11);
  }

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.accent);
  if (plan.hotel) {
    doc.text('Hotel', summaryRight, y + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.textPrimary);
    doc.text(`${plan.hotel.name} — ${plan.hotel.location}`, summaryRight, y + 6);
    doc.setTextColor(...colors.accentGold);
    doc.setFont('helvetica', 'bold');
    doc.text(`₹${plan.hotel.pricePerNight.toLocaleString()}/night`, summaryRight, y + 11);
  }

  y += 20;

  // ===== DAY-WISE ITINERARY =====
  const tabWidth = 22;
  const tabX = margin;
  const contentX = margin + tabWidth + 4;
  const cardRight = pageWidth - margin;
  const innerPad = 10;
  const actContentWidth = cardRight - contentX - innerPad;
  const priceRightX = cardRight - innerPad;

  for (const day of plan.itinerary) {
    const activityLines = day.activities.length;
    const mealLines = (day.meals?.lunch ? 1 : 0) + (day.meals?.dinner ? 1 : 0);
    const neededHeight = 22 + (activityLines + mealLines) * 10 + 10;

    checkPage(neededHeight);

    const tabColor = dayTabColors[(day.day - 1) % dayTabColors.length];
    const blockStartY = y;

    // Day content card background
    doc.setFillColor(...colors.cardBg);
    doc.roundedRect(contentX - 2, blockStartY, cardRight - contentX + 2, neededHeight - 2, 2, 2, 'F');

    // Vertical colored tab
    doc.setFillColor(...tabColor);
    doc.roundedRect(tabX, blockStartY, tabWidth, neededHeight - 2, 2, 2, 'F');

    // Day label (rotated & centered)
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.bgDark);
    const dayLabel = `DAY ${day.day}`;
    const tabCenterX = tabX + tabWidth / 2;
    const tabCenterY = blockStartY + (neededHeight - 2) / 2;
    doc.text(dayLabel, tabCenterX, tabCenterY, { align: 'center', angle: 90 });

    // Activity header
    let ay = blockStartY + 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.textPrimary);
    doc.text('Time', contentX + 6, ay);
    doc.text('Activity', contentX + 30, ay);

    // Weather + date info
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.textMuted);
    doc.text(`${day.date}  •  ${day.weather.temperature}°C, ${day.weather.condition}`, contentX + 70, ay);

    ay += 5;

    doc.setDrawColor(...colors.separator);
    doc.setLineWidth(0.3);
    doc.line(contentX + 6, ay, cardRight - 8, ay);

    ay += 7;

    // Activities
    for (const act of day.activities) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      doc.setTextColor(...colors.textMuted);
      const timeStr = act.timeSlot || '—';
      doc.text(timeStr, contentX + 6, ay);

      doc.setTextColor(...colors.textPrimary);
      const actName = act.name;
      const truncatedName = doc.splitTextToSize(actName, actContentWidth - 60);
      doc.text(truncatedName[0], contentX + 30, ay);

      const costStr = act.cost === 0 ? 'Free' : `₹${act.cost.toLocaleString()}`;
      doc.setTextColor(...tabColor);
      doc.setFont('helvetica', 'bold');
      doc.text(costStr, priceRightX, ay, { align: 'right' });

      ay += 9;
    }

    // Meals
    if (day.meals?.lunch) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...colors.textMuted);
      doc.text('Lunch', contentX + 6, ay);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.textPrimary);
      doc.text(`${day.meals.lunch.name} (${day.meals.lunch.cuisine})`, contentX + 30, ay);
      doc.setTextColor(...colors.accentGold);
      doc.setFont('helvetica', 'bold');
      doc.text(`₹${day.meals.lunch.costPerPerson}`, priceRightX, ay, { align: 'right' });
      ay += 9;
    }
    if (day.meals?.dinner) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...colors.textMuted);
      doc.text('Dinner', contentX + 6, ay);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.textPrimary);
      doc.text(`${day.meals.dinner.name} (${day.meals.dinner.cuisine})`, contentX + 30, ay);
      doc.setTextColor(...colors.accentGold);
      doc.setFont('helvetica', 'bold');
      doc.text(`₹${day.meals.dinner.costPerPerson}`, priceRightX, ay, { align: 'right' });
      ay += 9;
    }

    y = ay + 6;
  }

  // ===== COST BREAKDOWN =====
  if (plan.budgetBreakdown) {
    checkPage(70);
    y += 4;

    doc.setFillColor(...colors.accent);
    doc.roundedRect(margin, y - 5, contentWidth, 10, 1.5, 1.5, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.bgDark);
    doc.text('Cost Breakdown', margin + 6, y + 2);
    y += 14;

    const items = [
      ['Accommodation', plan.budgetBreakdown.accommodation],
      ['Transport', plan.budgetBreakdown.transport],
      ['Activities', plan.budgetBreakdown.activities],
      ['Food', plan.budgetBreakdown.food],
      ['Local Transport', plan.budgetBreakdown.localTransport || 0],
      ['Miscellaneous', plan.budgetBreakdown.miscellaneous],
    ] as const;

    for (let i = 0; i < items.length; i++) {
      const [label, val] = items[i];

      if (i % 2 === 0) {
        doc.setFillColor(...colors.cardBg);
        doc.rect(margin, y - 5, contentWidth, 9, 'F');
      }

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.textPrimary);
      doc.text(label, margin + 8, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.accentGold);
      doc.text(`₹${val.toLocaleString()}`, pageWidth - margin - 8, y, { align: 'right' });
      y += 9;
    }

    doc.setDrawColor(...colors.accent);
    doc.setLineWidth(0.5);
    doc.line(margin, y - 2, pageWidth - margin, y - 2);
    y += 5;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.accent);
    doc.text('TOTAL', margin + 8, y);
    doc.setTextColor(...colors.accentGold);
    doc.text(`₹${plan.totalCost.toLocaleString()}`, pageWidth - margin - 8, y, { align: 'right' });

    y += 8;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.textMuted);
    const statusText = plan.budgetStatus === 'approved'
      ? '✓ Within Budget'
      : plan.budgetStatus === 'warning'
        ? '⚠ Tight Budget'
        : '✗ Over Budget';
    doc.text(`Budget: ₹${plan.totalBudget.toLocaleString()}  •  ${statusText}`, margin + 6, y);
    y += 10;
  }

  // ===== TIPS =====
  if (plan.tips && plan.tips.length > 0) {
    checkPage(20);

    doc.setFillColor(...colors.cardBg);
    doc.roundedRect(margin, y - 4, contentWidth, 8, 1, 1, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.accent);
    doc.text('Travel Tips', margin + 4, y + 1);
    y += 10;

    for (const tip of plan.tips) {
      checkPage(10);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.textPrimary);
      const lines = doc.splitTextToSize(`• ${tip}`, contentWidth - 8);
      doc.text(lines, margin + 4, y);
      y += lines.length * 4.5 + 2;
    }
  }

  // ===== FOOTER =====
  addFooter();

  doc.save(`TravelPlan-${plan.destination.replace(/\s+/g, '-')}.pdf`);
}
